# Generated by Django 5.0.4 on 2026-01-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner', models.ImageField(upload_to='media')),
                ('nomi', models.CharField(max_length=50)),
                ('janr', models.CharField(max_length=50)),
                ('davlat', models.CharField(max_length=50)),
                ('yili', models.IntegerField()),
                ('davomiy', models.CharField(max_length=50)),
                ('tavsifi', models.TextField()),
            ],
        ),
    ]
