# Generated by Django 5.0.4 on 2026-01-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_movie',
            name='main_banner',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
