# Generated by Django 5.0.4 on 2026-01-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_main_movie_main_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_movie',
            name='video_img',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
