# Generated by Django 5.0.4 on 2026-01-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_main_movie_video_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner_purchase', models.ImageField(upload_to='media/')),
                ('nomi_purchase', models.CharField(max_length=50)),
                ('janr_purchase', models.CharField(max_length=50)),
                ('davlat_purchase', models.CharField(max_length=50)),
                ('yili_purchase', models.IntegerField()),
                ('davomiy_purchase', models.CharField(max_length=50)),
                ('tavsifi_purchase', models.TextField()),
                ('video_img_purchase', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
    ]
