# Generated by Django 5.0.4 on 2026-01-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_purchase_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_movie',
            name='is_premium',
            field=models.BooleanField(null=True),
        ),
    ]
